// 02_Angular/obligatorio/src/app/Components/login/login.component.ts
import { Component, OnInit } from '@angular/core';

import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm:FormGroup;
  constructor(public fb: FormBuilder, private authService: AuthService) { 
    this.loginForm = this.fb.group({
      email:['',[Validators.required, Validators.email]],
      password:['',[Validators.required]]
    })
  }

  ngOnInit(): void {
  }

  handleSubmit(): void {
    this.authService.loginUser(this.loginForm.value.email, this.loginForm.value.password);
    console.log("[LoginComponent] registerForm: ", this.loginForm);
  }

}

<section id="cont">
    <h2>Ingresar</h2>
    <div id="formulario" >
      <form [formGroup]="loginForm" (ngSubmit)="handleSubmit()">
        <input class="entradaFormulario" type="email" placeholder="Email" name="email" formControlName="email" />
        <input class="entradaFormulario" type="password" placeholder="Contraseña" name="password" formControlName="password" />
        <input class="entradaFormulario" type="submit" value="Enviar" [disabled]="loginForm.invalid"/>
      </form>
    </div>
    <!-- <h3>Alta de productos solo habilitada para el administrador. email: admin@zeus.com contraseña: 12345678</h3> --> 
    <h3 class="error" *ngIf="loginForm.get('email').hasError('required') && loginForm.get('email').dirty">El email es obligatorio</h3>
    <h3 class="error" *ngIf="loginForm.get('email').hasError('email') && loginForm.get('email').dirty">El email no tiene formato válido</h3>
    <h3 class="error" *ngIf="loginForm.get('password').hasError('required') && loginForm.get('password').dirty">La contraseña es obligatoria</h3>
</section>

// 01_React/module_03/src/components/Login/Login.js
import React, { Component, Fragment } from 'react';
import firebase from '../../config/firebase';
import GlobalContext from '../../GlobalState/GlobalContext';


class Login extends Component {
    static contextType = GlobalContext;
    constructor(props) {
        super(props);

    }

    adminCheck = (email) => {
        let isAdmin = false;
        firebase.firestore().collection("Admin").where("email", "==", email)
        .get()
        .then((querySnapshot)=>{
            querySnapshot.forEach(function(doc) {
            // doc.data() is never undefined for query doc snapshots
            console.log("[adminCheck] doc: ", doc);
            console.log("[adminCheck] doc.id: ", doc.id, " => ", doc.data());
            alert("[adminCheck] Administrador: Alta de productos habilitada");
            isAdmin = true;});
            if (isAdmin == true){this.context.setLoggedInAdmin();}}           
            )
        .catch(function(error) {
            console.log("Error getting documents: ", error);
        });

    }

    handleSubmit = (formLoginUserAdmin) => {
        formLoginUserAdmin.preventDefault();
        const LoginUserAdmin = {
            email : formLoginUserAdmin.target.email.value.toLowerCase(),
            password : formLoginUserAdmin.target.password.value
        }
        firebase.auth().signInWithEmailAndPassword(LoginUserAdmin.email, LoginUserAdmin.password)
        .then(()=>{
            alert("Usuario verificado, bienvenido!"  
            );
            let user = firebase.auth().currentUser;
            let userName;
            console.log("[handleSubmit] this.context.isLogging", this.context.isLogging);
            if (user != null) {
                userName = user.displayName.split("+");
                this.context.user = userName[0] + userName[1];
                this.context.setLoggedIn();
                console.log("[handleSubmit] this.context.isLogging", this.context.isLogging);
                this.adminCheck(LoginUserAdmin.email);
              }
        })
        .catch((error)=>{
            alert(error);
        });
   
        /* Cleaning form */
        formLoginUserAdmin.target.email.value = "";
        formLoginUserAdmin.target.password.value = "";
    }
    render() {
        return (
            <Fragment>
            <section id="cont">
                <h2>Ingresar</h2>
                <div id="formulario" onSubmit = {this.handleSubmit}>
                  <form >
                    <input className="entradaFormulario" type="email" placeholder="Email" name="email" required />
                    <input className="entradaFormulario" type="password" placeholder="Contraseña" name="password" required minLength="8" maxLength="14"/>
                    <input className="entradaFormulario" type="submit" value="Enviar"/>
                  </form>
                </div>
                <h3>Alta de productos solo habilitada para el administrador. email: admin@zeus.com contraseña: 12345678</h3>
            </section>      
            </Fragment>
        )
    }
}
export default Login;
