// 02_Angular/obligatorio/src/app/Components/store-product/store-product.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { modelStoreProduct } from '../../models/storeProduct/storeProduct'
import { Router } from '@angular/router';


@Component({
  selector: 'app-store-product',
  templateUrl: './store-product.component.html',
  styleUrls: ['./store-product.component.css']
})
export class StoreProductComponent implements OnInit {
  @Input() StoreProduct: modelStoreProduct;
  public buttonMSG: string;
  constructor(private router:Router) { }

  ngOnInit(): void {
  }

  clickCompra(): void {
    this.buttonMSG = "Muchas gracias por su compra!!"
    console.log("[StoreProductComponent] buttonMSG",  this.buttonMSG);  
  }

  clickDetalle(item_document_id): void {
    this.buttonMSG = "Ver mas detalles!!"
    console.log("[StoreProductComponent] item_document_id: ", item_document_id);      
    this.router.navigateByUrl("/detalle/" + item_document_id);
  }
}

<div class="storeProduct">
    <div class="storeProductIMG">
        <img src="{{StoreProduct.item_img}}" alt="{{StoreProduct.item_model}}" />
    </div>
    <div class="storeProductINFO">
    <ul>
        <li class="storeProductMark">Marca: {{StoreProduct.item_mark}}</li>
        <li class="storeProductModel">Descripción: modelo {{StoreProduct.item_model}}</li>
        <li class="storeProductPrice">Precio: {{StoreProduct.item_price}}</li>
        <li class="storeProductSKU">SKU: {{StoreProduct.item_sku}}</li>
    </ul>
    </div>
    <div class="buttonAndMSG">                    
        <button type="buttonBuy" (click)="clickCompra()" >Comprar</button>
        <button type="buttonDetails" (click)="clickDetalle(StoreProduct.item_document_id)" > Ver detalle</button>
        <p>{{buttonMSG}}</p>
    </div>
</div>

// 01_React/module_03/src/components/StoreProduct/StoreProduct.js
import React, { Component, Fragment } from 'react';
import { Link, Redirect } from 'react-router-dom'


class StoreProduct extends Component {
    constructor(props) {
        super(props);
        this.state = { buttonMSG: "",
                    redirect: false
            }
    }

    handleClick = (generator) => {
        if (generator === "BUTTON_BUY"){
            console.log( "Gracias por la compra!!" );
            this.setState({
                buttonMSG:"Gracias por la compra!!"
            });
        }
        else {
            console.log( "Boton de detalle ha sido presionado" );
            this.setState({...this.state,
                redirect: true
            });
        }
    }
    renderRedirect = () => {
        if (this.state.redirect) {
            return <Redirect to={"/detalle/" + this.props.storeProduct.id} />
        }
      }
    render() {
        return (
            <Fragment>
                {this.renderRedirect()}
                <div className="storeProduct">
                    <div className="storeProductIMG">
                        <img src={this.props.storeProduct.item_img} alt={this.props.storeProduct.item_model} />
                    </div>
                    <div className="storeProductINFO">
                    <ul>
                        <li className="storeProductMark">Marca: {this.props.storeProduct.item_mark}</li>
                        <li className="storeProductModel">Descripción: modelo {this.props.storeProduct.item_model}</li>
                        <li className="storeProductPrice">Precio: {this.props.storeProduct.item_price}</li>
                        <li className="storeProductSKU">SKU: {this.props.storeProduct.item_sku}</li>
                    </ul>
                    </div>
                    <div className="buttonAndMSG">                    
                        <button type="buttonBuy" onClick={ ()=>this.handleClick("BUTTON_BUY")} >Comprar</button>
                        <button type="buttonDetails" onClick={ ()=>this.handleClick("BUTTON_DETAILS")} > Ver detalle</button>
                        <p>{this.state.buttonMSG}</p>
                    </div>
                </div>      
            </Fragment>
        )
    }
}
export default StoreProduct;
