// 01_React/module_03/src/components/Register/Register.js
import React, { Component, Fragment } from 'react';
import firebase from '../../config/firebase';


class Register extends Component {
    constructor(props) {
        super(props);

    }
    handleSubmit = (formNewUser) => {
        formNewUser.preventDefault();
        console.log(formNewUser.target.firstname.value);
        console.log(formNewUser.target.lastname.value);
        console.log(formNewUser.target.email.value);
        console.log(formNewUser.target.password.value);
        /* Creating JSON with user data */ 
        const newUser = {
            firstname : formNewUser.target.firstname.value,
            lastname : formNewUser.target.lastname.value,
            email : formNewUser.target.email.value.toLowerCase(),
            password : formNewUser.target.password.value
        }
        
        firebase.auth().createUserWithEmailAndPassword(newUser.email, newUser.password).
        then(()=>{
            alert("Usuario Registrado");
            firebase.auth().currentUser.updateProfile(
                {displayName: newUser.firstname +"+"+newUser.lastname}
                )
            })
            .catch((error)=>{
                alert("Error");
                console.log(error);
            });
        
        /* Cleaning form */
        formNewUser.target.firstname.value = "";
        formNewUser.target.lastname.value = "";
        formNewUser.target.email.value = "";
        formNewUser.target.password.value = "";
    }
    render() {
        return (
            <Fragment>
            <section id="cont">
                <h2>Registrarse</h2>
                <div id="formulario" onSubmit = {this.handleSubmit}>
                  <form >
                    <input className="entradaFormulario" type="text" placeholder="Nombre" name="firstname" required/>
                    <input className="entradaFormulario" type="text" placeholder="Apellido" name="lastname" required />
                    <input className="entradaFormulario" type="email" placeholder="Email" name="email" required />
                    <input className="entradaFormulario" type="password" placeholder="Contraseña" name="password" required minLength="8" maxLength="14"/>
                    <input className="entradaFormulario" type="submit" value="Enviar"/>
                  </form>
                </div>
            </section>      
            </Fragment>
        )
    }
}
export default Register;

// 02_Angular/obligatorio/src/app/Components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  registerForm:FormGroup;
  constructor(public fb: FormBuilder) { 
    this.registerForm = this.fb.group({
      nombre:['',[Validators.required]],
      apellido:['',[Validators.required]],
      email:['',[Validators.required, Validators.email]],
      password:['',[Validators.required, Validators.minLength(8), Validators.maxLength(14) ]]
    })
  }

  ngOnInit(): void {
  }

  handleSubmit(): void {
    alert("registrado");
  }

}

<section id="cont">
    <h2>Registrarse</h2>
    <div id="formulario" >
      <form [formGroup]="registerForm" (ngSubmit)="handleSubmit()">
        <input class="entradaFormulario" type="text" placeholder="Nombre" name="nombre" formControlName="nombre" />
        <input class="entradaFormulario" type="text" placeholder="Apellido" name="apellido"  formControlName="apellido" />
        <input class="entradaFormulario" type="email" placeholder="Email" name="email" formControlName="email" />
        <input class="entradaFormulario" type="password" placeholder="Contraseña" name="password" formControlName="password" />
        <input class="entradaFormulario" type="submit" value="Enviar" [disabled]="registerForm.invalid"/>
      </form>
    </div>
    <h3 class="error" *ngIf="registerForm.get('nombre').hasError('required') && registerForm.get('nombre').dirty">El nombre es obligatorio</h3>
    <h3 class="error" *ngIf="registerForm.get('apellido').hasError('required') && registerForm.get('apellido').dirty">El apellido es obligatorio</h3>
    <h3 class="error" *ngIf="registerForm.get('email').hasError('required') && registerForm.get('email').dirty">El email es obligatorio</h3>
    <h3 class="error" *ngIf="registerForm.get('email').hasError('email') && registerForm.get('email').dirty">El email no tiene formato válido</h3>
    <h3 class="error" *ngIf="registerForm.get('password').hasError('required') && registerForm.get('password').dirty">La contraseña es obligatoria</h3>
    <h3 class="error" *ngIf="registerForm.get('password').hasError('minlength') && registerForm.get('password').dirty">La contraseña debe tener mínimo 8 caracteres</h3>
    <h3 class="error" *ngIf="registerForm.get('password').hasError('maxlength') && registerForm.get('password').dirty">La contraseña debe tener máximo 14 caracteres</h3>
</section>
