// 01_React/module_03/src/components/StoreProductDetailed/StoreProductDetailed.js
import React, { Component, Fragment } from 'react';
import firebase from '../../config/firebase';


class StoreProductDetailed extends Component {
    constructor(props) {
        super(props);
        this.state = { buttonMSG: "",
                    storeProduct: []
            }
    }
    componentDidMount(){
        /* Fetching product from database */
        firebase.firestore().collection("StoreProduct").doc(this.props.match.params.id).get()
        .then((doc) => { this.setState({...this.state,
            storeProduct:{ 
                item_img:doc.data().item_img,
                item_mark:doc.data().item_mark,
                item_model:doc.data().item_model,
                item_price:doc.data().item_price,
                item_sku:doc.data().item_sku,
                item_available:doc.data().item_available
                }
            })
            console.log("state",this.state);
        })
        .catch((error) => { });
    }
    handleClick = (generator) => {
        if (generator === "BUTTON_BUY"){
            console.log( "Gracias por la compra!!" );
            this.setState({
                buttonMSG:"Gracias por la compra!!"
            });
        }
        else {
            console.log( "Boton de detalle ha sido presionado" );
            this.setState({
                buttonMSG:"Boton de detalle ha sido presionado"
            });
        }
    }
    render() {
        return (
            <Fragment>
            <section id="cont">
                <div id="contTitle">
                    <h2>{this.state.storeProduct.item_model}</h2>
                </div>  
                <div className="storeGallery">
                    <div className="storeProduct">
                        <div className="storeProductIMG">
                            <img src={this.state.storeProduct.item_img} alt={this.state.storeProduct.item_model} />
                        </div>
                        <div className="storeProductINFO">
                        <ul>
                            <li className="storeProductMark">Marca: {this.state.storeProduct.item_mark}</li>
                            <li className="storeProductModel">Descripción: modelo {this.state.storeProduct.item_model}</li>
                            <li className="storeProductPrice">Precio: {this.state.storeProduct.item_price}</li>
                            <li className="storeProductSKU">SKU: {this.state.storeProduct.item_sku}</li>
                            <li className="storeProductAvailable">Cantidad disponible: {this.state.storeProduct.item_available}</li>
                        </ul>
                        </div>
                        <div className="buttonAndMSG">                    
                            <button type="buttonBuy" onClick={ ()=>this.handleClick("BUTTON_BUY")} >Comprar</button>
                            <p>{this.state.buttonMSG}</p>
                        </div>
                    </div>   
                </div>       
                </section>      
            </Fragment>
        )
    }
}
export default StoreProductDetailed;

// 02_Angular/obligatorio/src/app/Components/store-product-detailed/store-product-detailed.component.ts
import { Component, OnInit } from '@angular/core';

import { ActivatedRoute } from '@angular/router';
import { FirestoreService } from '../../services/firestore.service';
import { modelStoreProduct } from '../../models/storeProduct/storeProduct'

@Component({
  selector: 'app-store-product-detailed',
  templateUrl: './store-product-detailed.component.html',
  styleUrls: ['./store-product-detailed.component.css']
})
export class StoreProductDetailedComponent implements OnInit {
  public buttonMSG: string;
  public StoreProduct: modelStoreProduct;
  private _id: string;
  constructor(private route: ActivatedRoute, private firestoreService: FirestoreService) { }

  ngOnInit(): void {
    // Getting id document from HTTP
    this.route.params.subscribe(parametroHTTP => {
      this._id = parametroHTTP.id;
      console.log("[StoreProductDetailedComponent] _id: ", this._id );
    });
    // Getting data product from an id

    /*
    this.firestoreService.getStoreProduct(this._id).subscribe((StoreProductsSnapshot) => {
        console.log("[StoreProductDetailedComponent] StoreProductsSnapshot: ", StoreProductsSnapshot);
        this.StoreProduct = {
          item_document_id : StoreProductsSnapshot.payload.id,
          item_available : StoreProductsSnapshot.payload.data()['item_available'],
          item_img : StoreProductsSnapshot.payload.data()['item_img'],
          item_mark : StoreProductsSnapshot.payload.data()['item_mark'],
          item_model : StoreProductsSnapshot.payload.data()['item_model'],
          item_price : StoreProductsSnapshot.payload.data()['item_price'],
          item_sku : StoreProductsSnapshot.payload.data()['item_sku']
        };
        console.log("[StoreProductDetailedComponent] StoreProduct: ", this.StoreProduct);
    });
    */
   this.firestoreService.getStoreProduct(this._id).subscribe((StoreProductsSnapshot) => {
    console.log("[StoreProductDetailedComponent] StoreProductsSnapshot: ", StoreProductsSnapshot);
    this.StoreProduct = {
      item_document_id : StoreProductsSnapshot.id,
      item_available : StoreProductsSnapshot.data().item_available,
      item_img : StoreProductsSnapshot.data().item_img,
      item_mark : StoreProductsSnapshot.data().item_mark,
      item_model : StoreProductsSnapshot.data().item_model,
      item_price : StoreProductsSnapshot.data().item_price,
      item_sku : StoreProductsSnapshot.data().item_sku
    };
    console.log("[StoreProductDetailedComponent] StoreProduct: ", this.StoreProduct);
  });
}

  clickCompra(): void {
    this.buttonMSG = "Muchas gracias por su compra!!"
    console.log("[StoreProductDetailedComponent] buttonMSG",  this.buttonMSG);  
  }
}

<ng-container *ngIf="StoreProduct">
    <section id="cont">
        <div id="contTitle">
            <h2>{{StoreProduct.item_model}}</h2>
        </div>  
        <div class="storeGallery">
            <div class="storeProduct">
                <div class="storeProductIMG">
                    <img src="{{StoreProduct.item_img}}" alt="{{StoreProduct.item_model}}" >
                </div>
                <div class="storeProductINFO">
                <ul>
                    <li class="storeProductMark">Marca: {{StoreProduct.item_mark}}</li>
                    <li class="storeProductModel">Descripción: {{StoreProduct.item_model}}</li>
                    <li class="storeProductPrice">Precio: {{StoreProduct.item_price}}</li>
                    <li class="storeProductSKU">SKU: {{StoreProduct.item_sku}}</li>
                    <li class="storeProductAvailable">Cantidad disponible: {{StoreProduct.item_available}}</li>
                </ul>
                </div>
                <div class="buttonAndMSG">                    
                    <button type="buttonBuy" (click)="clickCompra()" >Comprar</button>
                    <p>{{buttonMSG}}</p>
                </div>
            </div>   
        </div>       
    </section>   
</ng-container>
